### ISSUE TITLE
Using with Swift AppDelegate

### ISSUE THREAD

**Issue by ugurerkan** [ByneappLLC/flutter_config#15]
Hello,

[There is sample for Objective-C](https://github.com/ByneappLLC/flutter_config/blob/master/doc/IOS.md#ios-advanced-setup) but my project is created with Swift and I can not figure out how to use flutter config in `ios/AppDelegate.swift` is there any example?

Maybe we can also provide this example in IOS readme.

Thank you in advance.

**Comment by andrzejmerix** [comment]
`import flutter_config`

and then you can use

`FlutterConfigPlugin.env(for: "SOME_KEY_FROM_ENV")`

@ugurerkan it's working for me with flutter 1.17.4

**Comment by AndrzejKaczynski** [comment]
`import flutter_config`

and then you can use

`FlutterConfigPlugin.env(for: "SOME_KEY_FROM_ENV")`

@ugurerkan it's working for me with flutter 1.17.4

**Comment by ugurerkan** [comment]
Thank you @AndrzejKaczynski

**Comment by lordvcs** [comment]
Doesnt seem to work on the latest
This is my AppDelegate.swift file
![image](https://user-images.githubusercontent.com/6374881/103125780-3a3aff00-46b2-11eb-8032-f427aa1c2cf3.png)
and this is the console output 
![image](https://user-images.githubusercontent.com/6374881/103125818-5dfe4500-46b2-11eb-9dc3-1f26082b36b1.png)

Am I doing something wrong?

**Comment by grapeworksdev** [comment]
I am running into the following error:
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file Runner/AppDelegate.swift, line 15

I have the following in my AppDelegate.swift file and my .env file. I also tried adding the following in my AppDelegate.m file
![Screen Shot 2021-05-25 at 16 12 06](https://user-images.githubusercontent.com/80786010/119562312-2e905900-bd74-11eb-99fe-7a117130323f.png)
![Screen Shot 2021-05-25 at 16 12 20](https://user-images.githubusercontent.com/80786010/119562319-30f2b300-bd74-11eb-8304-1e09b0885f67.png)
![Screen Shot 2021-05-25 at 16 14 18](https://user-images.githubusercontent.com/80786010/119562445-554e8f80-bd74-11eb-82bf-e413084ef163.png)

Any idea what's going on here?

**Comment by ldemyanenko** [comment]
This way with `import flutter_config` was working for me until I started using Flutter 2.8 and the latest version of the lib. Now I'm getting error 
    1 warning generated.
    /Users/builder/clone/ios/Runner/AppDelegate.swift:5:8: error: no such module 'flutter_config'
    import flutter_config
           ^
    /Users/builder/clone/ios/Runner/AppDelegate.swift:5:8: error: no such module 'flutter_config'
    import flutter_config
