### ISSUE TITLE
resValue string should not contain“

### ISSUE THREAD

**Issue by beilly** [ByneappLLC/flutter_config#18]
Generated from. Env string.xml The inclusion of "" will result in more references.

this is my ```.env```
![image](https://user-images.githubusercontent.com/7353956/92561296-8f3f3a80-f2a6-11ea-974d-bac99b7d07aa.png)

And this is ```string.xml```

![image](https://user-images.githubusercontent.com/7353956/92561392-b85fcb00-f2a6-11ea-9039-3a7f6ea0d323.png)

So. I think it should change
```
variant.resValue "string", k, "\"$escaped\""
```
to
```
variant.resValue "string", k, "$escaped"
```

![image](https://user-images.githubusercontent.com/7353956/92561101-2061e180-f2a6-11ea-886a-2924cefb7605.png)

**Comment by edTheGuy00** [comment]
This was merged and updated in Version 1.0.8
