### ISSUE TITLE
Does not work with Gradle version 4.0+

### ISSUE THREAD

**Issue by jamnaritesh** [ByneappLLC/flutter_config#31]
Hi Guys,
I'm trying to get this to work with below config:

=> flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/riteshsharma/Software/flutter
    • Framework revision 8f89f6505b (10 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/riteshsharma/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/riteshsharma/Desktop/runChromeWithoutSecurity

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • 

No issues found!

**gradle-wrapper.properties**
distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip

**android/Build.gradle:**
`dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }`

I get below errors with above settings:
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/riteshsharma/.pub-cache/hosted/pub.dartlang.org/flutter_config-1.0.8/android/dotenv.gradle' line: 87
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:generateDebugBuildConfig'.              
> No signature of method: com.android.build.gradle.internal.variant.ApplicationVariantData.getVariantConfiguration() is applicable for argument types: () values: []
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 20s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        21.0s
Exception: Gradle task assembleDebug failed with exit code 1

================================

I think the latest version 1.0.8 does not work because of breaking changes in gradle.

I made changes to line 87 as suggested here, and got it working.
Can you let me know if i have something wrong?

https://stackoverflow.com/questions/62075122/no-such-property-variantconfiguration-for-class

**Comment by ShamarKellman** [comment]
@jamnaritesh can you post the exact code change you made? I am trying to upgrade and ran into the same issue. Thanks

**Comment by jamnaritesh** [comment]
@ShamarKellman I forked this repo, and on my pubspec.yml I used the git repo instead of using any specific version. 

https://github.com/quanngovan98/flutter_config

**Comment by edTheGuy00** [comment]
This was fixed with #26 . I'll update it on pub.dev as soon as #34 is merged.

**Comment by edTheGuy00** [comment]
Version 2.0.0 has been [published](https://pub.dev/packages/flutter_config) with gradle 4.0 support

**Comment by amanv8060** [comment]
@edTheGuy00 it doesn't works with gradle 7.0.0 , required to use jetpack compose 

```
* Where:
Script '/home/amanv8060/.pub-cache/hosted/pub.dartlang.org/flutter_config-2.0.0/android/dotenv.gradle' line: 92

* What went wrong:
Execution failed for task ':app:generateProductionDebugBuildConfig'.
> The value for property 'buildConfigFields' is final and cannot be changed any further.

```

**Comment by dovahkrid** [comment]
This seems to be the fix from the react version

https://github.com/luggit/react-native-config/pull/609

You can edit the dotenv.gradle file yourself if this lib doesn't get an update.

**Comment by hazzo** [comment]
@edTheGuy00 it's seems that this fix is not pushed tu `pub.dev`. The actual code that you change in version 2.0 installed on my app for the `dotenv.gradle` file has this at the end:

```

tasks.whenTaskAdded { task ->
    if (project.hasProperty("envConfigFiles")) {
        project.envConfigFiles.each { envConfigName, envConfigFile ->
            if (task.name.toLowerCase() == "generate"+envConfigName+"buildconfig") {
                task.doFirst() {
                    android.applicationVariants.all { variant ->
                       def variantConfigString = variant.getName()
                        if (envConfigName.contains(variantConfigString.toLowerCase())) {
                            loadDotEnv(envConfigName)
                            project.env.each { k, v ->
                                def escaped = v.replaceAll("%","\\\\u0025")
                                variant.buildConfigField "String", k, "\"$v\""
                                variant.resValue "string", k, "$escaped"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

instead of this that is the actual code of the repository.

```
tasks.whenTaskAdded { task ->
    if (project.hasProperty("envConfigFiles")) {
        project.envConfigFiles.each { envConfigName, envConfigFile ->
            if (task.name.toLowerCase() == "generate" + envConfigName + "buildconfig") {

                android.applicationVariants.all { variant ->
                    def variantConfigString = variant.getName()
                    if (envConfigName.contains(variantConfigString.toLowerCase())) {
                        loadDotEnv(envConfigName)
                        project.env.each { k, v ->
                            def escaped = v.replaceAll("%", "\\\\u0025")
                            variant.buildConfigField "String", k, "\"$v\""
                            variant.resValue "string", k, "$escaped"
                        }
                    }
                }

            }
        }
    }
}
```
I added to my `pubspec.yaml` as a git dependency and it's working fine.
