### ISSUE TITLE
Does not work in release mode with http.get

### ISSUE THREAD

**Issue by nehamallama** [ByneappLLC/flutter_config#32]
When you run on release mode,  you cant add anything to the base url given by flutter config. dart http is extremely wide used and should be supported in release mode. Issue only occurs in android. Half a day down the drain because of this one here......
```
 var r = await http.get(FlutterConfig.get('BASE_URL') + '/login',
        headers: <String, String>{'authorization': basicAuth});
    _isLoading = true;
```
Yields the error --> E/flutter ( 3278): Receiver: null
E/flutter ( 3278): Tried calling: +("/login")
E/flutter ( 3278): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54)
E/flutter ( 3278): #1      _MainPageState.getDeviceDetails (package:fpw_ui_android/main.dart:96)
E/flutter ( 3278): <asynchronous suspension>
E/flutter ( 3278):

**Comment by nehamallama** [comment]
RUN AWAY! They dont update anything or respond to any open issues. Use this dep instead https://pub.dev/packages/flutter_dotenv

**Comment by edTheGuy00** [comment]
Your issue is most likely because you don't have a `proguard-rules.pro` file. This was discussed over a year ago in #4 
and was added on the README by #28  But instead of searching previous issues or reading the README you chose to come here and complain.
