### ISSUE TITLE
Add null safety

### ISSUE THREAD

**Issue by moioo91120** [ByneappLLC/flutter_config#33]
Hello,

Any way to add Null Safety to this package ? 

Thanks

**Comment by pecostef** [comment]
Hello! I opened a PR in order to add null safety support: https://github.com/ByneappLLC/flutter_config/pull/34

**Comment by steven-spiel** [comment]
This is really important for our team. Can you check on that PR? @byneapp

**Comment by edTheGuy00** [comment]
Hey guys, thanks. Weirdly enough I didn't receive any notifications until @steven-spiel . I'll look into right away

**Comment by edTheGuy00** [comment]
@pecostef Looks, good. I've just added a few recommendations on what I believe might be a better approach.

**Comment by edTheGuy00** [comment]
Version 2.0.0 has been [published](https://pub.dev/packages/flutter_config)  Thanks @pecostef for the PR
