### ISSUE TITLE
Different environments when build apk in release mode is null

### ISSUE THREAD

**Issue by hungthai1401** [ByneappLLC/flutter_config#4]
I have set that:
```
project.ext.envConfigFiles = [
    debug: ".env.development",
    release: ".env.production",
]
```

But when run ```flutter build apk```,  ```FlutterConfig.get('DUMMY')``` always return null.

**Comment by edTheGuy00** [comment]
@hungthai1401 Can you share your app `build.gradle` file ?

**Comment by hungthai1401** [comment]
@edTheGuy00 , this is my app ```build.gradle``` file

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

project.ext.envConfigFiles = [
    debug: ".env.development",
    release: ".env.production",
]

apply from: project(':flutter_config').projectDir.getPath() + "/dotenv.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.hd.hd"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

```

**Comment by stpch** [comment]
I'm having the same problem without using different environments. It looks like there's an issue with building the app through the flutter command.

Running `flutter build appbundle` gives me `null` when using `FlutterConfig.get(...)`. However, it works when running `./gradlew assembleRelease` from the `android` directory.

**Comment by edTheGuy00** [comment]
@stpch try `flutter build appbundle --flavor YOUR_FLAVOR`

This is how I have it setup on my production apps, so I just run either

`flutter build appbundle --flavor prod `

or 

`flutter build appbundle --flavor dev`

the flavor being what I defined in the app gradle as shown in the [example app](https://github.com/ByneappLLC/flutter_config/blob/f102f10e1de52a1f305c5bf072ed3c9eda65fdf6/example/android/app/build.gradle#L68)

**Comment by stpch** [comment]
Shouldn't it work without flavors? https://github.com/luggit/react-native-config (which this project seems inspired by) works like this, where flavors are completely optional.

I'd imagine most people start out without flavors and add them later in development if needed.

**Comment by edTheGuy00** [comment]
@stpch Yes it should work without flavors. I haven't had much time to debug this issue. I'll look into the in the coming days. 

It would be great if someone could help out 😃

**Comment by martynasadomaitis** [comment]
I think I found the solution. I had the problem when i get `null` on any `FlutterConfig.get('DUMMY')` with a release build using `flutter build apk --release` or `flutter build appbundle --release` (debug mode works OK and returns config values correctly).

After digging into `flutter_config` code, I found a line in `FlutterConfigPlugin.kt`:

```
val clazz = Class.forName("$className.BuildConfig")
```

In other words - reflection is used to retrieve `BuildConfig` class for your application which has all your env variables. However, when we use `--release` flag with flutter command - an R8 obfuscator kicks in and changes className `BuildConfig` to something else - thus this line of code results in `ClassNotFoundException` and provides no env vars.

**SOLUTION**

To prevent obfuscation of `BuildConfig`, add R8 obfuscator rule to keep class intact:

1. Add file `android/app/proguard-rules.pro` to your app's project.
2. Add this line to created file:

```
-keep class com.yourcompany.app.BuildConfig { *; }
```

where replace `com.yourcompany.app` with your app's package name.

This solved the problem for me - release build now returns env vars as expected. I did not use any flavors.

**Comment by israellias** [comment]
@martynasadomaitis you saved my day! and probably my startup!
Thanks!

**Comment by alfredma1117** [comment]
Thank you @martynasadomaitis !

**Comment by nathan-cb8** [comment]
thank you @martynasadomaitis - can we get this added to docs - from what I can see it still isn't listed

**Comment by lordvcs** [comment]
Thanks for the plugin but please add this to the documentation, I spent some hours trying to figure this out.

**Comment by eherediadev** [comment]
I'm using flavors and this is the error I'm getting:

```
Reading env from: .env
**************************
*** Missing .env file ****
**************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevelopmentDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Home\App\Projects\lask\android\app\src\main\AndroidManifest.xml:35:5-36:54: AAPT: error: resource string/GOOGLE_MAPS_API_KEY (aka com.example.laskdev:string/GOOGLE_MAPS_API_KEY) not found.

```

**Comment by 4A-Dilla** [comment]
This didn't work for me, I'm having the same issue trying to use proguard and flutter config
`
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

project.ext.envConfigFiles = [
        developmentdebug: ".env",
        developmentrelease: ".env",
        productiondebug: ".env",
        productionrelease: ".env",
]

apply from: project(':flutter_config').projectDir.getPath() + "/dotenv.gradle"


android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
        abortOnError false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.nci.nf_kicks"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            signingConfig signingConfigs.release
            useProguard true
            minifyEnabled true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            // TODO: Add your own signing config for the release build.
            signingConfig signingConfigs.debug
            useProguard true
            minifyEnabled true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:26.1.0')
    implementation 'com.google.firebase:firebase-analytics'
}

apply plugin: 'com.google.gms.google-services'
`

**Comment by 4A-Dilla** [comment]
Found the solution,  add ```-keep class com.YourPackageName.BuildConfig { *; }``` to android/app/proguard-rules.pro

**Comment by edTheGuy00** [comment]
I'm closing this as it seems to have been a proguard-rules.pro related issued. README was update with #28
