### ISSUE TITLE
flavors using same app_id

### ISSUE THREAD

**Issue by ramuramasani** [ByneappLLC/flutter_config#43]
I'm using flutter _config in my project when I use different flavors app using same app_id instead of different app_id's

**Comment by mdeandrea-mrmilu** [comment]
This is a question? Is solved?

**Comment by edTheGuy00** [comment]
Not sure what your question is... flutter_config always reads `.env` file by default unless you explicitly specify other `.env.other` files to read from. If you want to use the same `.env` for all your flavors then you don't really need to do anything.
