### ISSUE TITLE
help me: I can not run ios 

### ISSUE THREAD

**Issue by Datnguyenvan09** [ByneappLLC/flutter_config#49]
When i run ios app with flavor:

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/yd/1kdc_grd1l9frs2gjg5lg7s40000gn/T/flutter_tools.rmuM6A/flutter_ios_build_temp_dirDk8Bct/temporary_xcresult_bundle

    reading env file from /Users/dat/StudioProjects/test_config/ios/ and writing .config to /Users/dat/StudioProjects/test_config/ios/Flutter/tmp.xcconfig
    going to read env file from root folder /Users/dat/StudioProjects/test_config/ios/
    file exists at /Users/dat/StudioProjects/test_config/ios/.envfile
    path /Users/dat/StudioProjects/test_config/.env.staging

    Failed to package /Users/dat/StudioProjects/test_config.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

    Result bundle written to path:
    	/var/folders/yd/1kdc_grd1l9frs2gjg5lg7s40000gn/T/flutter_tools.rmuM6A/flutter_ios_build_temp_dirDk8Bct/temporary_xcresult_bundle

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

Pls help me:

**Comment by ssorrychoi** [comment]
I have also same issue. Did you resolve it?

**Comment by edTheGuy00** [comment]
Hi, these are just logs that are being output by [BuildDotenvConfig.rb](https://github.com/ByneappLLC/flutter_config/blob/ed3a01f687526a58bed79b804c38c3481ae34108/ios/Classes/BuildDotenvConfig.rb#L8) , I don't see any specific error related to `flutter_config` 

Please look for the `error` line in your Xcode output.
