### ISSUE TITLE
Not compatible with Flutter Web

### ISSUE THREAD

**Issue by jamie1192** [ByneappLLC/flutter_config#5]
The [pub.dev listing ](https://pub.dev/packages/flutter_config) notes the package as being compatible with Flutter Web but doesn't work at all. The page should remove the web support tag if it doesn't support it please.

**Comment by edTheGuy00** [comment]
@jamie1192 It would be nice if someone could help bring support for web 😃

**Comment by edTheGuy00** [comment]
Web label has been automatically removed thanks to [the new plugin platforms map](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms)
