### ISSUE TITLE
Could not access BuildConfig

### ISSUE THREAD

**Issue by bonaregoapp** [ByneappLLC/flutter_config#8]
Although I've followed the installation process, I'm getting this log message
D/FlutterConfig( 6446): Could not access BuildConfig
".env" file exists in root of the project.

android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply from: project(':flutter_config').projectDir.getPath() + "/dotenv.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.danef.danef_dictionary"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

**Comment by Puttz** [comment]
same as me

**Comment by hubahuba** [comment]
i got same error message when i try to add flavor into my app and use applicationIdSuffix, 
but solved when i add `defaultConfig` with:
`
resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST.XML"
`
as per android setup mention

> if you use applicationIdSuffix or applicationId that is different from the package name indicated in AndroidManifest.xml in <manifest package="..."> tag

maybe you should check your AndroidManifest package name or try to add `resValue` into your `defaultConfig`

**Comment by edTheGuy00** [comment]
> i got same error message when i try to add flavor into my app and use applicationIdSuffix,
> but solved when i add `defaultConfig` with:
> `resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST.XML"`
> as per android setup mention
> 
> > if you use applicationIdSuffix or applicationId that is different from the package name indicated in AndroidManifest.xml in  tag
> 
> maybe you should check your AndroidManifest package name or try to add `resValue` into your `defaultConfig`

@bonaregoapp did this solve your issue? 👆

**Comment by edTheGuy00** [comment]
Closing due to no response

**Comment by ducquynhnguyeninfo** [comment]
Got the same issue and this solution is not clear to understand. Could you please add an example?

> i got same error message when i try to add flavor into my app and use applicationIdSuffix,
> but solved when i add `defaultConfig` with:
> `resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST.XML"`
> as per android setup mention
> 
> > if you use applicationIdSuffix or applicationId that is different from the package name indicated in AndroidManifest.xml in  tag
> 
> maybe you should check your AndroidManifest package name or try to add `resValue` into your `defaultConfig`

**Comment by igonzarec** [comment]
> i got same error message when i try to add flavor into my app and use applicationIdSuffix, but solved when i add `defaultConfig` with: `resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST.XML"` as per android setup mention
> 
> > if you use applicationIdSuffix or applicationId that is different from the package name indicated in AndroidManifest.xml in  tag
> 
> maybe you should check your AndroidManifest package name or try to add `resValue` into your `defaultConfig`

This indeed solved the issue for me as well.
